import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "@/context/AuthContext";
import NavBar from "@/components/header/NavBar";
import AppDrawer from "@/layout/AppDrawer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="creatheme" lang="pt-br">
      <body className={inter.className}>
        <AuthProvider>
          <AppDrawer>
            <NavBar />
            {children}
          </AppDrawer>
        </AuthProvider>
      </body>
    </html>
  );
}
